added sessions 7
BatoolMM/from-Zero-to-hero-in-r pull request #23
Opened 2022-07-30 18:05 UTC by Anhal-77

2022-08-02 09:32 UTC, BatoolMM requested changes
I love the plot, can you try to change the theme and the title of X and y axis

2022-08-02 09:32 UTC, BatoolMM commented on working_sessions/HOMEWORK-ANHAL.Rmd
> +library(plotly)
why did you add `plotly` if you aren't suing it during the code?

2022-08-02 09:32 UTC, BatoolMM commented on working_sessions/HOMEWORK-ANHAL.Rmd
> +coffee %>%
This is fantastic but you have created above a new variable `co`to store the new dataframe. However, you didn't use it when you created the plot
```suggestion
co %>%
```

2022-08-04 01:17 UTC, Anhal-77 commented
> I love the plot, can you try to change the theme and the title of X and y axis

I did it ✅

2022-08-09 21:39 UTC, Anhal-77 commented
added sessions

2022-08-14 12:36 UTC, BatoolMM commented
![](https://media.giphy.com/media/czubJ08i7deuKGJE9A/giphy.gif)

2022-08-14 12:37 UTC, BatoolMM approved these changes

2022-08-14 12:37 UTC, merged

2023-01-07 12:37 UTC, BatoolMM commented
@all-contributors please add @Anhal-77 for Answering Questions